/**
 * User-visible copy in one place (easy to tweak later).
 */
export const strings = {
  appName: 'Y VAA',
  homeTagline: 'Anti-cheat quiz & viva — setup ready.',
  loginTitle: 'Log in',
  signUpTitle: 'Create account',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  confirmPasswordLabel: 'Confirm password',
  displayNameLabel: 'Display name (optional)',
  roleLabel: 'I am a',
  teacherRole: 'Teacher',
  studentRole: 'Student',
  loginCta: 'Log in',
  signUpCta: 'Sign up',
  goToSignUp: 'Need an account? Sign up',
  goToLogin: 'Already have an account? Log in',
  signOut: 'Sign out',
  missingEnvTitle: 'Configuration needed',
  missingEnvBody:
    'Add EXPO_PUBLIC_SUPABASE_URL (must be https://YOUR_REF.supabase.co from Project Settings → API, not the dashboard link) and EXPO_PUBLIC_SUPABASE_ANON_KEY (publishable key, or legacy anon JWT starting with eyJ…). No spaces or quotes. Save .env, stop Expo (Ctrl+C), run: npx expo start -c',
  teacherHomeSubtitle: 'Create a quiz and share the room code with students.',
  studentHomeSubtitle: 'Enter the room code from your teacher to start.',
  createQuizCta: 'Create quiz',
  createQuizTitle: 'New quiz',
  quizTitleLabel: 'Quiz title',
  quizTitlePlaceholder: 'e.g. Unit 2 revision',
  quizMinutesLabel: 'Time limit (minutes)',
  quizMinutesInvalid: 'Use a number between 1 and 240 minutes.',
  quizTitleRequired: 'Please enter a quiz title.',
  quizQuestionEmpty: 'Every question needs text.',
  quizMcqOptionsInvalid: 'Each MCQ needs at least two non-empty options.',
  questionLabel: 'Q',
  questionTextPlaceholder: 'Type the question',
  optionLabel: 'Option',
  addOptionCta: '+ Add option',
  addQuestionCta: '+ Add another question',
  saveQuizCta: 'Save quiz',
  quizCreatedTitle: 'Quiz created',
  roomCodeInputLabel: 'Room code',
  joinRoomCta: 'Join quiz',
  roomCodeInvalid: 'Enter the 6-character room code.',
  roomCodeLabel: 'Room code',
  timeLimitLabel: 'Time limit',
  noQuizzesYet: 'No quizzes yet — tap Create quiz.',
  loadingQuestions: 'Loading questions…',
  textAnswerPlaceholder: 'Type your answer',
  submitQuizCta: 'Submit answers',
  submittedTitle: 'Submitted',
  submittedBody: 'Your answers were saved.',
  timeUpTitle: "Time's up",
  timeUpBody: 'Your quiz was submitted automatically.',
  errorTitle: 'Something went wrong',
  back: 'Back',
  ok: 'OK',
};
